"""empty message

Revision ID: 14fb3af97396
Revises: 20d14004f237
Create Date: 2022-10-18 02:35:48.923548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14fb3af97396'
down_revision = '20d14004f237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('spaces_name_key', 'spaces', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('spaces_name_key', 'spaces', ['name'])
    # ### end Alembic commands ###
