"""empty message

Revision ID: 45cf0c92af16
Revises: 60e3bce0ba19
Create Date: 2022-10-28 19:44:31.645064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45cf0c92af16'
down_revision = '60e3bce0ba19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_unique_constraint(None, 'user', ['lastname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
