"""empty message

Revision ID: 604a453535f2
Revises: 48c03edb2260
Create Date: 2022-10-25 01:40:26.625883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '604a453535f2'
down_revision = '48c03edb2260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('myspaces_message_key', 'myspaces', type_='unique')
    op.drop_column('myspaces', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myspaces', sa.Column('message', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.create_unique_constraint('myspaces_message_key', 'myspaces', ['message'])
    # ### end Alembic commands ###
